language: python
python:
  - "2.7"
branches:
  only:
    - elvis_development
install:
  - pip install coveralls
  - pip install coverage
  - pip install -r pipeline_elvis/requirements.txt
script:
  - cd pipeline_elvis/tests
  - nosetests test_checkOptions.py
  - nosetests test_checkInit.py
#  - nosetests test_failedOptions.py
#  - nosetests test_failedFullPipelineSteps.py
#  - nosetests test_splitMethodCheckElvis.py
#  - nosetests test_cleanMethodCheckElvis.py
#  - nosetests test_sextractorMethodCheckElvis.py
  - coverage run -a test_checkOptions.py
  - coverage run -a test_checkInit.py
#  - coverage run -a test_failedOptions.py
#  - coverage run -a test_failedFullPipelineSteps.py
#  - coverage run -a test_splitMethodCheckElvis.py
#  - coverage run -a test_cleanMethodCheckElvis.py
#  - coverage run -a test_sextractorMethodCheckElvis.py
after_success:
  - coverage combine
  - coverage report -m -i --omit '/home/travis/virtualenv/*'
  - coveralls --rcfile='/home/travis/build/sgongar/Euclid-tests/.coveragerc'
