language: python
python:
  - "2.7"
branches:
  only:
    - elvis_development
install:
  - pwd
  # - sudo apt-get install -y python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose
  - sudo apt-get install python2-twisted
  - pip install -r pipeline_elvis/requirements.txt
script:
  - cd tests
  - trial test_checkOptions.py
#   - nosetests --nocapture --with-coverage TestFailedOptions.py
  - coverage run test_checkOptions.py