language: python
python:
  - "2.7"
cache: pip
before_install:
- sudo apt-get install -y python-virtualenv
install:
  - pip install -r pipeline/modules.txt
script:
  - python -m unittest discover -s tests