language: python
python:
  - "2.7"
branches:
  only:
    - elvis_development
install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
  - pip install -r pipeline_elvis/requirements.txt
script:
  - cd tests
  - trial test_checkOptions.py
  - trial test_failedOptions.py
  - trial test_failedFullPipelineSteps.py
  - trial test_splitMethodCheckElvis.py
  - coverage run test_*.py

after_success:
  - coverage combine
  - coverage report --omit '/home/travis/virtualenv/*'
  - coveralls