language: python
python:
  - "2.7"
branches:
  only:
    - elvis_development
install:
  - pip install coveralls
  - pip install coverage
  - pip install -r pipeline_elvis/requirements.txt
script:
  - cd tests
  - trial test_checkOptions.py
  - trial test_failedOptions.py
  - trial test_failedFullPipelineSteps.py
  - trial test_splitMethodCheckElvis.py
  - trial test_cleanMethodCheckElvis.py
  - trial test_sextractorMethodCheckElvis.py
  # - coverage run -a test_checkOptions.py
  - coverage run -a test_failedOptions.py
  - coverage run -a test_failedFullPipelineSteps.py
  - coverage run -a test_splitMethodCheckElvis.py
  - coverage run -a test_cleanMethodCheckElvis.py
  - coverage run -a test_sextractorMethodCheckElvis.py

after_success:
  - coverage report -i --omit '/home/travis/virtualenv/*'
  - coveralls --rcfile='/home/travis/build/sgongar/Euclid-tests/.coveragerc'