#!/bin/bash
# get filename
echo -n "Enter File Name : "
read fileName
# make sure file exits for reading
if [ ! -f $fileName ]; then
    echo "Filename $fileName does not exists"
    exit 1
fi
# display last five lines of the file using tail command
tail -5 $fileName
